In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('./Datasets/covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
df.isna().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [4]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(['has_covid'],axis=1),df['has_covid'],test_size=0.2)

In [6]:
X_train

age  gender  fever   cough       city
70   68  Female  101.0  Strong      Delhi
18   64  Female   98.0    Mild  Bangalore
99   10  Female   98.0  Strong    Kolkata
87   47    Male  101.0  Strong  Bangalore
8    19  Female  100.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
40   49  Female  102.0    Mild      Delhi
91   38    Male    NaN    Mild      Delhi
49   44    Male  104.0    Mild     Mumbai
74   34  Female  104.0  Strong      Delhi
41   82    Male    NaN    Mild    Kolkata

[80 rows x 5 columns]

In [7]:
y_train

70     No
18    Yes
99    Yes
87     No
8      No
     ... 
40     No
91    Yes
49     No
74     No
41    Yes
Name: has_covid, Length: 80, dtype: object

## Do all the things column wise , column by column

In [9]:
si=SimpleImputer()

# adding simple imputer for fever column

X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [15]:
X_train_fever

array([[101.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [103.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [102.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [103.        ],
       [101.        ],
       [104.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [101.02816901],
       [104.        ],
       [ 99

In [20]:
# Ordinal Encoding ---> Cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [21]:
X_test_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [12]:
ohe=OneHotEncoder(drop='first',sparse=False)
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])

c:\Users\Arushi Prajapati\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
c:\Users\Arushi Prajapati\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [13]:
X_train_gender_city

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],


In [14]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [18]:
X_train_age.shape,X_train_fever.shape,X_train_gender_city.shape,X_train_cough.shape

((80, 1), (80, 1), (80, 4), (80, 1))

In [22]:
X_test_age.shape,X_test_fever.shape,X_test_gender_city.shape,X_test_cough.shape

((20, 1), (20, 1), (20, 4), (20, 1))

In [23]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)



In [25]:
X_train_df=pd.DataFrame(X_train_transformed,columns=['Age','fever','gender','cityA','cityB','cityC','cough'])

In [26]:
X_train_df.head()

Age  fever  gender  cityA  cityB  cityC  cough
0  68.0  101.0     0.0    1.0    0.0    0.0    1.0
1  64.0   98.0     0.0    0.0    0.0    0.0    0.0
2  10.0   98.0     0.0    0.0    1.0    0.0    1.0
3  47.0  101.0     1.0    0.0    0.0    0.0    1.0
4  19.0  100.0     0.0    0.0    0.0    0.0    1.0

In [27]:
X_train_df.isna().sum()

Age       0
fever     0
gender    0
cityA     0
cityB     0
cityC     0
cough     0
dtype: int64

## Column Transformer

In [28]:
from sklearn.compose import ColumnTransformer

In [29]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first',sparse=False),['gender','city'])
],remainder='passthrough')

In [30]:
transformer.fit_transform(X_train)

c:\Users\Arushi Prajapati\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  68.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.    

In [31]:
transformer.fit_transform(X_train).shape

c:\Users\Arushi Prajapati\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [32]:
transformer.transform(X_test)

array([[101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.    

In [33]:
transformer.transform(X_test).shape

(20, 7)